# Generated by Django 5.0.4 on 2024-04-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpayment',
            old_name='value',
            new_name='gross_amount',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='value',
            new_name='gross_amount',
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='net_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='discount_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='discounted_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='product_code',
            field=models.CharField(default='ABC123', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='net_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='discounted_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(default='ABC123', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
    ]
