# Generated by Django 5.0.4 on 2024-04-23 18:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0002_rename_value_historicalpayment_gross_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=16)),
                ('type', models.CharField(choices=[('seller_coupon', 'SELLER_COUPON'), ('seller_offer', 'SELLER_OFFER'), ('platform_coupon', 'PLATFORM_COUPON'), ('platform_offer', 'PLATFORM_OFFER')], max_length=32)),
                ('value_type', models.CharField(choices=[('fixed', 'FIXED'), ('percentage', 'PERCENTAGE')], max_length=32)),
                ('value', models.FloatField(default=0)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='historicalorder',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='historicalpayment',
            name='discount_value',
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='discount_value',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='discount_value',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_value',
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shopping_cart.order'),
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='shopping_cart.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='discount',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shopping_cart.discount'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='discount',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shopping_cart.discount'),
        ),
        migrations.AddField(
            model_name='payment',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shopping_cart.discount'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shopping_cart.discount'),
        ),
    ]
