# Generated by Django 5.0.4 on 2024-04-23 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0003_discount_remove_historicalorder_payment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='product_code',
            new_name='discount_code',
        ),
    ]
