# Generated by Django 5.0.4 on 2024-04-24 00:12

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0004_rename_product_code_discount_discount_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpayment',
            name='discount_applied',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='discount_applied',
        ),
        migrations.AddField(
            model_name='discount',
            name='mode',
            field=models.CharField(blank=True, choices=[('cash', 'CASH'), ('debit', 'DEBIT_CARD'), ('credit', 'CREDIT_CARD'), ('upi', 'UPI'), ('net_banking', 'NET_BANKING'), ('emi_debit', 'EMI_DEBIT_CARD'), ('emi_credit', 'EMI_CREDIT_CARD'), ('later', 'PAY_LATER'), ('wallet', 'WALLET_INHOUSE'), ('wallet_external', 'WALLET_THIRD_PARTY')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='type',
            field=models.CharField(choices=[('seller_coupon', 'SELLER_COUPON'), ('seller_offer', 'SELLER_OFFER'), ('platform_coupon', 'PLATFORM_COUPON'), ('platform_offer', 'PLATFORM_OFFER'), ('payment_mode_coupon', 'PAYMENT_MODE_COUPON'), ('payment_mode_offer', 'PAYMENT_MODE_OFFER')], max_length=32),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='status',
            field=models.CharField(choices=[('placed', 'PLACED'), ('processed', 'PROCESSED'), ('packed', 'PACKED'), ('shipped', 'SHIPPED'), ('delivered', 'DELIVERED'), ('return_placed', 'RETURN_PLACED'), ('return_picked', 'RETURN_PICKED'), ('return_processed', 'RETURN_PROCESSED'), ('return_shipped', 'RETURN_SHIPPED'), ('return_delivered', 'RETURN_DELIVERED')], max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('placed', 'PLACED'), ('processed', 'PROCESSED'), ('packed', 'PACKED'), ('shipped', 'SHIPPED'), ('delivered', 'DELIVERED'), ('return_placed', 'RETURN_PLACED'), ('return_picked', 'RETURN_PICKED'), ('return_processed', 'RETURN_PROCESSED'), ('return_shipped', 'RETURN_SHIPPED'), ('return_delivered', 'RETURN_DELIVERED')], max_length=32),
        ),
        migrations.CreateModel(
            name='HistoricalDiscount',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('discount_code', models.CharField(max_length=16)),
                ('type', models.CharField(choices=[('seller_coupon', 'SELLER_COUPON'), ('seller_offer', 'SELLER_OFFER'), ('platform_coupon', 'PLATFORM_COUPON'), ('platform_offer', 'PLATFORM_OFFER'), ('payment_mode_coupon', 'PAYMENT_MODE_COUPON'), ('payment_mode_offer', 'PAYMENT_MODE_OFFER')], max_length=32)),
                ('mode', models.CharField(blank=True, choices=[('cash', 'CASH'), ('debit', 'DEBIT_CARD'), ('credit', 'CREDIT_CARD'), ('upi', 'UPI'), ('net_banking', 'NET_BANKING'), ('emi_debit', 'EMI_DEBIT_CARD'), ('emi_credit', 'EMI_CREDIT_CARD'), ('later', 'PAY_LATER'), ('wallet', 'WALLET_INHOUSE'), ('wallet_external', 'WALLET_THIRD_PARTY')], max_length=32, null=True)),
                ('value_type', models.CharField(choices=[('fixed', 'FIXED'), ('percentage', 'PERCENTAGE')], max_length=32)),
                ('value', models.FloatField(default=0)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(default=django.utils.timezone.now)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical discount',
                'verbose_name_plural': 'historical discounts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
